<item>
   <title>Issue #888 created</title>
   <pubDate>2023-12-09T23:31:39Z</pubDate>
   <link>https://github.com/qt4cg/qtspecs/issues/888</link>
   <guid>https://qt4cg.org/@qt4cg/2023/#created-888</guid>
   <description>&lt;div&gt;&lt;p&gt;Reclassify XPDY0002 as a type error&lt;/p&gt;&lt;div class="markup"&gt;&lt;p&gt;I propose to reclassify XPDY0002 (context item is absent) as a type error rather than a dynamic error.&lt;/p&gt;
&lt;p&gt;I don't propose to change the error code.&lt;/p&gt;
&lt;p&gt;The only practical distinction is that this will allow the error to be reported statically when it can be detected statically, for example if the user writes something like&lt;/p&gt;
&lt;pre&gt;&lt;code&gt;function($x as node()) {
  starts-with(name(), 'x')
}
&lt;/code&gt;&lt;/pre&gt;
&lt;p&gt;At present Saxon will give you a compile-time warning for this, followed by a run-time error if the code is actually executed; this is the required behaviour for dynamic errors.&lt;/p&gt;
&lt;p&gt;The change does mean that in a case like this example, it will no longer be possible to catch the error using try/catch. However, type errors can only be reported statically if the code is bound to fail at run-time, and catching errors that occur every time is not especially useful.&lt;/p&gt;
&lt;/div&gt;&lt;/div&gt;</description>
</item>
